package com.android.hikepeaks.Models;

import android.graphics.Bitmap;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIgnore;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.ElementList;
import org.simpleframework.xml.Root;

import java.util.ArrayList;

@DynamoDBTable(tableName = "Accounts")
@Root
public class Account {
    @Element(required = false)
    private String id;
    @Element(required = false)
    private String displayName;
    @Element(required = false)
    private String email;
    @Element(required = false)
    private String pictureUrl;
    private Bitmap pictureBitmap;

    @ElementList(name = "trails", required = false)
    private ArrayList<Trail> trails = new ArrayList<>();

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "DisplayName")
    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    @DynamoDBAttribute(attributeName = "Email")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @DynamoDBAttribute(attributeName = "PictureUrl")
    public String getPictureUrl() {
        return pictureUrl;
    }

    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl;
    }

    @DynamoDBIgnore
    public ArrayList<Trail> getTrails() {
        return trails;
    }

    public void setTrails(ArrayList<Trail> trails) {
        this.trails = trails;
    }

    public void addTrail(Trail myTrail) {
        this.trails.add(myTrail);
    }

    @DynamoDBIgnore
    public Bitmap getPictureBitmap() {
        return pictureBitmap;
    }

    public void setPictureBitmap(Bitmap pictureBitmap) {
        this.pictureBitmap = pictureBitmap;
    }
}
